# Generated by Django 3.0.1 on 2020-01-01 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commodity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityDetail',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('activity_name', models.CharField(max_length=15)),
                ('activity_info', models.CharField(blank=True, max_length=50, null=True)),
                ('activity_status', models.PositiveIntegerField()),
                ('create_time', models.DateTimeField()),
                ('update_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'activity_detail',
            },
        ),
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=10)),
                ('create_time', models.DateTimeField()),
                ('update_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'activity_type',
            },
        ),
        migrations.CreateModel(
            name='RelActivityCommodity',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField()),
                ('update_time', models.DateTimeField(blank=True, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='activity.ActivityDetail')),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='commodity.CommodityDetail')),
            ],
            options={
                'db_table': 'rel_activity_commodity',
            },
        ),
        migrations.AddField(
            model_name='activitydetail',
            name='activity_type',
            field=models.ForeignKey(db_column='activity_type', on_delete=django.db.models.deletion.DO_NOTHING, to='activity.ActivityType'),
        ),
    ]
