# Generated by Django 3.0.1 on 2020-01-02 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0005_auto_20200102_1543'),
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitydetail',
            options={'verbose_name': '活动详情', 'verbose_name_plural': '活动详情'},
        ),
        migrations.AlterModelOptions(
            name='activitytype',
            options={'verbose_name': '活动类型', 'verbose_name_plural': '活动类型'},
        ),
        migrations.AlterModelOptions(
            name='relactivitycommodity',
            options={'verbose_name': '活动商品', 'verbose_name_plural': '活动商品'},
        ),
        migrations.AlterField(
            model_name='activitydetail',
            name='activity_info',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='活动详情'),
        ),
        migrations.AlterField(
            model_name='activitydetail',
            name='activity_name',
            field=models.CharField(max_length=15, verbose_name='活动名称'),
        ),
        migrations.AlterField(
            model_name='activitydetail',
            name='activity_status',
            field=models.PositiveIntegerField(choices=[(0, '未上线'), (1, '已上线')], default=0, verbose_name='活动状态'),
        ),
        migrations.AlterField(
            model_name='activitydetail',
            name='activity_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.ActivityType', verbose_name='活动类型'),
        ),
        migrations.AlterField(
            model_name='activitydetail',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='activitydetail',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='序号'),
        ),
        migrations.AlterField(
            model_name='activitydetail',
            name='update_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='activitytype',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='activitytype',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='序号'),
        ),
        migrations.AlterField(
            model_name='activitytype',
            name='type_name',
            field=models.CharField(max_length=10, verbose_name='类型名称'),
        ),
        migrations.AlterField(
            model_name='activitytype',
            name='update_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='relactivitycommodity',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.ActivityDetail', verbose_name='活动名称'),
        ),
        migrations.AlterField(
            model_name='relactivitycommodity',
            name='commodity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commodity.CommodityDetail', verbose_name='商品名称'),
        ),
        migrations.AlterField(
            model_name='relactivitycommodity',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='relactivitycommodity',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='序号'),
        ),
        migrations.AlterField(
            model_name='relactivitycommodity',
            name='update_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间'),
        ),
    ]
