# Generated by Django 3.0.1 on 2020-01-04 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_auto_20200104_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitydetail',
            name='activity_status',
            field=models.PositiveIntegerField(choices=[(0, '已结束'), (1, '未开始'), (2, '进行中'), (-1, '失效活动')], default=0, verbose_name='活动状态'),
        ),
    ]
