# Generated by Django 3.0.1 on 2020-01-02 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartdetail',
            name='is_deleted',
            field=models.PositiveIntegerField(choices=[(0, '未删除'), (1, '已删除')], default=0, verbose_name='是否删除'),
        ),
        migrations.AlterField(
            model_name='cartdetail',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, '未购买'), (1, '已购买')], default=0, verbose_name='是否购买'),
        ),
        migrations.AlterField(
            model_name='userorder',
            name='payment_type',
            field=models.PositiveIntegerField(choices=[(0, '支付宝'), (1, '微信')], verbose_name='支付类型'),
        ),
    ]
