# Generated by Django 3.0.1 on 2020-01-02 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200102_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='email',
            field=models.CharField(default='1@qq.com', max_length=100, verbose_name='邮箱'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='nickname',
            field=models.CharField(default='syk', max_length=50, verbose_name='昵称'),
            preserve_default=False,
        ),
    ]
