# Generated by Django 3.0.1 on 2020-01-03 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200103_0452'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='gender',
            field=models.PositiveIntegerField(choices=[(0, '男性'), (1, '女性')], default=0, verbose_name='性别'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='phone',
            field=models.CharField(default='13685733162', max_length=100, verbose_name='手机号'),
            preserve_default=False,
        ),
    ]
