# Generated by Django 3.0.1 on 2020-01-03 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200103_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='gender',
            field=models.PositiveIntegerField(choices=[(0, '男'), (1, '女')], verbose_name='性别'),
        ),
    ]
