# Generated by Django 3.0.1 on 2020-01-03 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200103_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='gender',
            field=models.PositiveIntegerField(choices=[(0, '男'), (1, '女')], default=0, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='phone',
            field=models.CharField(default='123456', max_length=100, verbose_name='手机号'),
        ),
    ]
