# Generated by Django 3.0.1 on 2020-01-01 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommodityImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('image_url', models.CharField(max_length=100, verbose_name='图片地址')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间')),
                ('is_deleted', models.PositiveIntegerField(default=0, verbose_name='是否删除')),
            ],
            options={
                'db_table': 'commodity_image',
            },
        ),
        migrations.CreateModel(
            name='CommodityType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('type_name', models.CharField(max_length=10, unique=True, verbose_name='商品类型')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_date', models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间')),
                ('is_deleted', models.PositiveIntegerField(default=0, verbose_name='是否删除')),
                ('parent_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commodity.CommodityType', verbose_name='上一级分类')),
            ],
            options={
                'db_table': 'commodity_type',
            },
        ),
        migrations.CreateModel(
            name='CommodityDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('commodity_name', models.CharField(max_length=255, verbose_name='商品名称')),
                ('commodity_info', models.CharField(max_length=255, verbose_name='商品描述')),
                ('commodity_price', models.PositiveIntegerField(verbose_name='商品单价')),
                ('commodity_status', models.PositiveIntegerField(default=0, verbose_name='商品状态')),
                ('commodity_pics', models.CharField(blank=True, max_length=255, null=True, verbose_name='商品图片')),
                ('is_discount', models.PositiveIntegerField(default=0, verbose_name='是否打折')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间')),
                ('is_deleted', models.PositiveIntegerField(default=0, verbose_name='是否删除')),
                ('commodity_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='commodity.CommodityType', verbose_name='商品类型')),
            ],
            options={
                'verbose_name': '商品信息',
                'verbose_name_plural': '商品信息',
                'db_table': 'commodity_detail',
            },
        ),
    ]
