# Generated by Django 3.0.1 on 2020-01-02 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commodityimage',
            options={'verbose_name': '商品图片', 'verbose_name_plural': '商品图片'},
        ),
        migrations.AlterModelOptions(
            name='commoditytype',
            options={'verbose_name': '商品类型', 'verbose_name_plural': '商品类型'},
        ),
        migrations.AddField(
            model_name='commodityimage',
            name='commodity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='commodity.CommodityDetail', verbose_name='商品'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commoditydetail',
            name='commodity_status',
            field=models.PositiveIntegerField(choices=[(0, '上架'), (1, '下架'), (2, '预售')], default=0, verbose_name='商品状态'),
        ),
    ]
