# Generated by Django 3.0.1 on 2020-01-02 07:43

import commodity.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0004_auto_20200102_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodityimage',
            name='commodity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commodity.CommodityDetail', verbose_name='商品名称'),
        ),
        migrations.AlterField(
            model_name='commodityimage',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to=commodity.models.CommodityImage.img_path, verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='commoditytype',
            name='is_deleted',
            field=models.PositiveIntegerField(choices=[(0, '未删除'), (1, '已删除')], default=0, verbose_name='是否删除'),
        ),
    ]
