# Generated by Django 3.0.1 on 2020-01-02 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0006_auto_20200102_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commoditytype',
            name='parent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='commodity.CommodityType', verbose_name='上一级分类'),
        ),
    ]
