# Generated by Django 3.0.1 on 2020-01-02 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0007_auto_20200103_0321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commoditytype',
            name='parent_id',
        ),
        migrations.AddField(
            model_name='commoditytype',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pid', to='commodity.CommodityType', verbose_name='上一级分类'),
        ),
    ]
