# Generated by Django 3.0.1 on 2020-01-01 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('commodity_id', models.IntegerField()),
                ('commodity_name', models.CharField(max_length=20)),
                ('commodity_price', models.PositiveIntegerField()),
                ('commodity_amount', models.PositiveSmallIntegerField()),
                ('commodity_discount', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('commodity_image', models.CharField(max_length=100)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.UserOrder')),
            ],
            options={
                'db_table': 'order_detail',
            },
        ),
    ]
