# Generated by Django 3.0.1 on 2020-01-02 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200102_1619'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderdetail',
            options={'verbose_name': '订单详情', 'verbose_name_plural': '订单详情'},
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='commodity_amount',
            field=models.PositiveSmallIntegerField(verbose_name='商品数量'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='commodity_discount',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='商品折扣'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='commodity_id',
            field=models.IntegerField(verbose_name='商品号'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='commodity_image',
            field=models.CharField(max_length=100, verbose_name='商品图片'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='commodity_name',
            field=models.CharField(max_length=20, verbose_name='商品名称'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='commodity_price',
            field=models.PositiveIntegerField(verbose_name='商品单价'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='序号'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserOrder', verbose_name='订单号'),
        ),
    ]
