# Generated by Django 3.0.1 on 2020-01-03 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20200102_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='commodity_image',
            field=models.CharField(max_length=300, verbose_name='商品图片'),
        ),
    ]
