# Generated by Django 3.0.1 on 2020-01-03 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20200103_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='序号'),
        ),
    ]
